name: 'V2EX2WorkWechat'
description: 'GitHub Action for V2EX stories'
author: 'hackee'
branding:
  icon: 'arrow-right-circle'
  color: 'gray-dark'
inputs:
  webhook:
    description: 'webhook url'
    required: true
  secret:
    description: 'signature key'
    required: false
    default: ''
  count:
    description: 'number of hot stories the user wants to get'
    required: false
    default: 8
outputs:
  result:
    description: 'The result of api'
runs:
  using: 'docker'
  image: 'Dockerfile'
