name: V2ex


on: # [push, pull_request]
  schedule:
    # 可自定义 cron 表达式
    - cron: '0 2-11 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: yanglbme/v2ex-action@v1.0.3
        with:
          webhook: ${{ secrets.WEBHOOK }}
          secret: ${{ secrets.SECRET }}
          count: 8
